---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: falcon
    box: "jborean93/${MOLECULE_DISTRO:-WindowsServer2019}"
    box_version: 1.0.0
    memory: 4096
    cpus: 2
    # interfaces:
    #   - network_name: private_network
    #     ip: 192.168.50.20
    # config_options:
    #   vm.communicator: "'winrm'"
provisioner:
  name: ansible
  inventory:
    host_vars:
      falcon:
        ansible_become: False
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 55986
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  test_sequence:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
