---
# tasks file for falcon_uninstall
- name: Linux Block
  when:
    - ansible_facts['os_family'] != "Windows"
  become: true
  become_user: root
  block:
    - ansible.builtin.include_tasks: uninstall.yml
      # noqa name[missing]

- name: Windows Block
  when:
    - ansible_facts['os_family'] == "Windows"
  become: true
  become_method: "{{ falcon_windows_become_method }}"
  become_user: "{{ falcon_windows_become_user }}"
  block:
    - ansible.builtin.include_tasks: win_uninstall.yml
      # noqa name[missing]
