---
- name: CrowdStrike Falcon | Authenticate to CrowdStrike API
  ansible.windows.win_uri:
    url: "https://{{ falcon_cloud }}/oauth2/token"
    method: POST
    body:
      "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: true
    follow_redirects: all
    status_code: [201, 308]
    headers:
      content-type: "application/x-www-form-urlencoded; charset=utf-8"
  register: falcon_api_oauth2_token_win
  no_log: "{{ falcon_api_enable_no_log }}"
  run_once: true

- name: CrowdStrike Falcon | Configure discovered CrowdStrike Cloud Region
  ansible.builtin.set_fact:
      falcon_cloud: "{{ falcon_cloud_urls[falcon_api_oauth2_token_win.x_cs_region] }}"
  when:
    - falcon_cloud_autodiscover
    - falcon_api_oauth2_token_win.x_cs_region | length > 0

# With win_uri - the follow_redirects: all option does not work as expected.
# The following task is a workaround to follow the redirect once we get a 308 response.
- name: CrowdStrike Falcon | Authenticate to CrowdStrike API (follow redirect)
  ansible.windows.win_uri:
    url: "https://{{ falcon_cloud }}/oauth2/token"
    method: POST
    body:
      "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: true
    follow_redirects: all
    status_code: [201]
    headers:
      content-type: "application/x-www-form-urlencoded; charset=utf-8"
  register: falcon_api_oauth2_token_win_redirect
  no_log: "{{ falcon_api_enable_no_log }}"
  run_once: true
  when: falcon_api_oauth2_token_win.status_code == 308

- name: CrowdStrike Falcon | Set Appropriate API OAuth2 Token
  ansible.builtin.set_fact:
    falcon_api_oauth2_token: "{{ falcon_api_oauth2_token_win_redirect if falcon_api_oauth2_token_win_redirect.json is defined else falcon_api_oauth2_token_win }}"
  no_log: "{{ falcon_api_enable_no_log }}"

- name: Set falcon_cid Block
  when: not falcon_cid
  block:
  - name: CrowdStrike Falcon | Detect Target CID Based on Credentials
    ansible.windows.win_uri:
      url: https://{{ falcon_cloud }}/sensors/queries/installers/ccid/v1
      method: GET
      return_content: true
      headers:
        authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
        Content-Type: application/json
    register: falcon_api_target_cid_win
    no_log: "{{ falcon_api_enable_no_log }}"
    run_once: true

  - name: CrowdStrike Falcon | Set CID received from API
    ansible.builtin.set_fact:
      falcon_cid: "{{ falcon_api_target_cid_win.json.resources[0] }}"
