download_url: https://galaxy.ansible.com/download/devsec-hardening-8.6.0.tar.gz
format_version: 1.0.0
name: hardening
namespace: devsec
server: https://galaxy.ansible.com/api/
signatures: []
version: 8.6.0
version_url: https://galaxy.ansible.com/api/v2/collections/devsec/hardening/versions/8.6.0/
