---
- name: default server playbook
  hosts: all
  become: true
  become_method: sudo
  strategy: free
  timeout: 60

  tasks:
    - name: Upgrade
      package:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Upgrade
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'
