---

- name: devsec os hardening
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  collections:
    - devsec.hardening

  roles:
    - role: os_hardening
      tags:
        - os
